version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  # postgres_testing:
  #   container_name: postgres_testing
  #   image: postgres:latest
  #   ports:
  #     - "5433:5432"
  #   volumes:
  #     - ./postgres-testing-data:/var/lib/postgresql/data
  #   environment:
  #     - POSTGRES_USER=postgres_testing
  #     - POSTGRES_PASSWORD=postgres_testing
  #     - POSTGRES_DB=postgres_testing